### ISSUE TITLE
Build failing due to missing Position on  geolocate-control.directive.d.ts

### ISSUE THREAD

**Issue by mlicciardi** [Wykks/ngx-mapbox-gl#257]
As well of the build failing due to the Layer import ([open issue here](https://github.com/Wykks/ngx-mapbox-gl/issues/256)) my build is build failing here too:
```
Error: node_modules/ngx-mapbox-gl/lib/control/geolocate-control.directive.d.ts:13:29 - error TS2304: Cannot find name 'Position'.

13     geolocate: EventEmitter<Position>;
```

package.json devDependencies
```
    "@types/mapbox-gl": "^1.12.8",
    "mapbox-gl": "^1.13.0",
    "@types/node": "^14.14.10",
    "typescript": "^4.1.2"
```

**Comment by dmytro-gokun** [comment]
@mlicciardi Does this still happen with @types/mapbox-gl >= 1.12.9?

**Comment by Wykks** [comment]
Hi @mlicciardi 

Looks like something changed in recent version of typescript. For now, ngx-mapbox-gl is not compatible with typescript 4.1.x

**Comment by rlmestre** [comment]
Per [@types/geojson](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts#L34-L41), `Position` is just an (type) alias for `[number, number, number?]`. Maybe it can be declared directly here? By adding it manually the error goes away, but I haven't tested it yet since I don't use `mglGeolocate`.

**Comment by dmytro-gokun** [comment]
@rlmestre Please check if the problem exists with 6.0.1

**Comment by rlmestre** [comment]
It does compile on 6.0.1 but it's importing the wrong `Position` interface. My previous comment was also incorrect on the matter. TypeScript updated their DOM lib and as a result `Position` was renamed to `GeolocationPosition`. 6.0.1 is importing a different interface from `@angular/compiler` which is unrelated.

**Comment by dmytro-gokun** [comment]
Closed via #276, released in v6.0.2
