### ISSUE TITLE
Has no exported member 'Alignment' in @types/mapbox-gl

### ISSUE THREAD

**Issue by PouyaKrm** [Wykks/ngx-mapbox-gl#237]
> ERROR in node_modules/ngx-mapbox-gl/lib/map/map.service.d.ts:5:10 - error TS2305: Module '"../../../@types/mapbox-gl"' has no exported member 'Alignment'

 This occurs on compiling **Angular version 9.1.12** project.

**Comment by PouyaKrm** [comment]
**Update** 
`ngx-mapbox-gl`,  ` mapbox-gl@0.54.0 ` and `@types/mapbox-gl@0.51.10` are used

**Comment by dmytro-gokun** [comment]
@PouyaKrm so, why do not you try updating to the latest versions of those libraries?

**Comment by dmytro-gokun** [comment]
ngx-mapbox-gl actually have a peerDependency "mapbox-gl": "^1.1.0", it is not guaranteed to work with "0.54.0". You should see a warning in console about that when doing "npm install"

**Comment by PouyaKrm** [comment]
> @PouyaKrm so, why do not you try updating to the latest versions of those libraries?

These version were specified in README file of repository

**Comment by dmytro-gokun** [comment]
@PouyaKrm Okay, fair point. I've updated README so that it does not nadate which version to install. This means the latest available version will be installed. Please let me know if everything works fine for you when using the latest versions of ngx-mapbox-gl, mapbox-gl and @types/mapbox-gl.

**Comment by PouyaKrm** [comment]
using latest version of @types/mapbox-gl(version 1.1.0) fixed the problem.
Thanks for updating README
