### ISSUE TITLE
Build failed: "Could not find a declaration file for module '@mapbox/mapbox-gl-geocoder'"

### ISSUE THREAD

**Issue by lassschr** [Wykks/ngx-mapbox-gl#263]
Hi, just installed ngx-mapbox-gl following the given instructions and have ran into the following problem stated below.
I am using:
* Angular 11.0.1
* @types/mapbox-gl 2.0.0
* mapbox-gl 2.0.1
* ngx-mapbox-gl 5.0.0
* typescript 4.0.2
* @mapbox/mapbox-gl-geocoder 4.7.0

`Error: node_modules/ngx-mapbox-gl/lib/control/geocoder-control.directive.d.ts:2:33 - error TS7016: Could not find a declaration file for module '@mapbox/mapbox-gl-geocoder'. *ROOT*/node_modules/ngx-mapbox-gl/node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/mapbox__mapbox-gl-geocoder` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/mapbox-gl-geocoder';`

2 import * as MapboxGeocoder from '@mapbox/mapbox-gl-geocoder';`

**Comment by salmoro** [comment]
Have same issue with Angular 10.1.3.
As a temporary fix I rolled back to 4.8.1.

**Comment by dmytro-gokun** [comment]
@lassschr Does the problem still exist with v6.0.1?

**Comment by lassschr** [comment]
> @lassschr Does the problem still exist with v6.0.1?

Yes - and now there is also an issue in the same file "geocoder-control.directive.ts" when exporting { Result, Results } from @mapbox/mapbox-gl-geocoder on line 8:

node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js' implicitly has an 'any' type

**Comment by lassschr** [comment]
> @lassschr Does the problem still exist with v6.0.1?

After updating to v6.0.1:

Error: node_modules/ngx-mapbox-gl/lib/control/geocoder-control.directive.d.ts:2:55 - error TS7016: Could not find a declaration file for module '@mapbox/mapbox-gl-geocoder'. 'ROOT/node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/mapbox__mapbox-gl-geocoder` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/mapbox-gl-geocoder';`

2 import MapboxGeocoder, { Result, LngLatLiteral } from '@mapbox/mapbox-gl-geocoder';
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-mapbox-gl/lib/control/geocoder-control.directive.d.ts:9:33 - error TS7016: Could not find a declaration file for module '@mapbox/mapbox-gl-geocoder'. 'ROOT/node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/mapbox__mapbox-gl-geocoder` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/mapbox-gl-geocoder';`

9 export { Result, Results } from '@mapbox/mapbox-gl-geocoder';

**Comment by lassschr** [comment]
> @lassschr Does the problem still exist with v6.0.1?

After updating to v6.0.1 and running the following command:

npm install @types/mapbox__mapbox-gl-geocoder

The error is now gone and I will close this issue.

**Comment by Vegita2** [comment]
This should be added to the readme

**Comment by wesco-abhisheksuresh** [comment]
It gives the same error in the version 7.0.9

**Comment by wesco-abhisheksuresh** [comment]
in react

**Comment by itpmanis** [comment]
issue solved
 npm install @types/mapbox__mapbox-gl-geocoder
